[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# solc_version = "0.8.20"
optimizer_runs = 10_000_000

remappings = [
	"@openzeppelin/=lib/openzeppelin/",
]

[fmt]
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}", chain = 137 }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
